### ISSUE TITLE
Incorrect work Zend_Date::getTime

### ISSUE THREAD

**Issue by pwsdotru** [Shardj/zf1-future#152]
Zend_Date::getTime() for default constructor return current time and date for 1 Jan 1970. But I think it should return current date too.

Tested on last release and PHP 7.4.20

Code for reproduce
```
<?php

require('vendor/autoload.php');

$now = new Zend_Date();

echo($now->getTime());
echo("\n");
echo(date("c"));
echo("\n");
```

Output

```
Jan 1, 1970 12:12:49 PM
2021-06-11T12:12:49+00:00
```

**Comment by rruchte** [comment]
The way the date part accessor methods  work in ZendDate is unusual in that they reset all parts of the date other then the requested part to January 1, 1970 and return the full date, but the behavior is definitely intentional, this is not a bug. I am not sure WHY it was designed this way, there is nothing in Zend_Date itself or elsewhere in the framework that depends on this as far as I can tell. My guess is that it could potentially make comparisons of date parts easier. For instance, if you wanted to know the difference between events on different days in terms of time of day, say 3:00 yesterday and 3:15 the day before should result in 15 minutes, this approach would make that easier. But you would probably be better off using DateTime and DateInterval for that kind of thing. I get the feeling that a lot of the code in Zend_Date may have been written before DateTime was introduced, so it tries to do a lot of the same things, just not as well.

I don't think that changing the Zend_Date::getTime() to return the current date makes sense, because you would logically then need to change the other part accessors to work the same way, and then they would all return exactly the same thing, a full representation of the current date, which makes even less sense that it does now. I think that if a change were to be made (and I do **not** think that any changes should be made here), the part accessors should be changed to only return the requested date part, which would be much more intuitive. However this could potentially be a breaking change for users who depend on the current behavior, and I don't see much benefit, given PHP's ample date manipulation facilities.

It's interesting that the documentation does not even mention these methods, it's almost as if they were intended for a purpose that was never implemented.

@pwsdotru  for your specific purposes, if you really want to use Zend_Date, the Zend_Date::get() method is probably what you should use.

```
<?php

$now = new Zend_Date();

// Get current time
echo $now->get("HH:mm:ss").PHP_EOL;

// Get current ISO 8601 using Zend_Date
echo $now->get("c").PHP_EOL;

// Get current ISO 8601 using Zend_Date convenience method
echo $now->getIso().PHP_EOL;

// Get current ISO 8601 date using PHP date
echo date("c").PHP_EOL;
```
Output:
```
10:35:06
2021-06-11T10:35:06-04:00
2021-06-11T10:35:06-04:00
2021-06-11T10:35:06-04:00
```
