### ISSUE TITLE
ZF1-Future getting some positive press!

### ISSUE THREAD

**Issue by WebTigers** [Shardj/zf1-future#183]
Not really an "issue" to fix. Just wanted to alert everyone that I have a new article up on Medium and Reddit giving ZF1-Future some positive press!

Medium
[ZendFramework 1—Reborn!](https://beau-beauchamp.medium.com/zendframework-1-reborn-b0226b77f34)

**Comment by Pooky** [comment]
Very well written! Thanks for that =)

P.S. I have same opinion on the ZF2 and ZF3 - I never understood, why they put so much pressure on dependency injection and configuration stuff. I tried that but get back to old ZF1. In my opinion, if you wanna this kind of stuff just use JAVA instead of PHP =)

**Comment by Shardj** [comment]
Awesome!
