### ISSUE TITLE
Form filter not PHP 8.1 compatibille

### ISSUE THREAD

**Issue by develart-projects** [Shardj/zf1-future#243]
Hi, seems that Filetrs have problems with named parameters, therefore it's not working for PHP 8.1.

Definition in form::init() (example):

`// phone
        $this->addElement('text','customerPhone', array (
                                                'label'=> 'Phone',
                                                'required' => TRUE,
                                                'filters'   => Array(
                                                                'StringTrim',
                                                                ['PregReplace', ['match' => '/\s+/', 'replace' => ''] ] // remove white spaces
                                                ),
                                                'validators' => Array(
                                                                    Array('StringLength', false, array(2))
                                                                )
                                            )
        );`

Error:

_Unknown named parameter $match_

Any idea how this should be solved? Thank you.
Ivan

**Comment by develart-projects** [comment]
Seems that

['match' => '/\s+/', 'replace' => '']

..is going into Filter constructor and that's where issue pops up.

**Comment by develart-projects** [comment]
Did more research, problem is related to the

Zend/Form/Element, line 2119

There is code

`$instance = $r->newInstanceArgs((array) $filter['options']);`

If it's single array, it's decoupled into named args and therefore it fails.
So workarrout is to wrap it inside another array in the Zend_Form::init() definition.

Not sure if we can solve this on the ZF1 level. Seems to me like PHP8 bug. Or undocummented feature of ReflectionClass::newInstanceArgs()

**Comment by topicode** [comment]
As I wrote in #246 (since I didn't read this issue here, shame on me), this bug was reintroduced with the current release `1.21.3`, and I am not sure if reverting back to the behaviour of `1.21.2` causes any problems somewhere.

**Comment by develart-projects** [comment]
I did exactly the same change, but in the INIT(), not in the ZF lib and running currently under 7.4 to test. Seems to be working OK.

**Comment by topicode** [comment]
After reading the reason for the change back to the original ZF1 version in https://github.com/Shardj/zf1-future/pull/186#issuecomment-1060931720, I think that we have to deal with passing the options as individual arguments instead of as an array.

I propose the following solution instead (untested, but I think it should work): pass the options through `array_values()`, i.e. `$r->newInstanceArgs(array_values((array) $filter['options']));`. Since this passes the arguments "normally", and not named, the error should go away. For pre-PHP 8 code it does not make any difference, since the option names were irrelevant anyways, but the order mattered. For new PHP 8 code it *could* have an impact, but I doubt that this feature is currently in use in ZF1 projects (at least at this point).
The only disadvantage is that this solution removes the possibility to use named arguments in this case in the future, but I think that that is not really a problem.

I can test that on monday and create a PR if it works.

**Comment by topicode** [comment]
So, I created a PR (but assigned it to the other issue, #246, since I had the tab still open... sorry for that).

The solution should be a viable way to go, but with the named drawback of not supporting named parameters there.

It might be better to rewrite the use of the filters in each project to pass the options really as array (so the options have to be wrapped in another array), since then the order of the arguments is irrelevant, as the use of the keys already suggests.

**Comment by Shardj** [comment]
Merged https://github.com/Shardj/zf1-future/pull/249
