### ISSUE TITLE
PHP 8.2 - Deprecate dynamic properties 

### ISSUE THREAD

**Issue by icyz** [Shardj/zf1-future#307]
hello everyone, 
is it planned to face the problem of "Creation of dynamic property"? I don't know, but this will be a bit painful.

`Deprecated: Creation of dynamic property Zend_View::$var is deprecated`

**Comment by Hikariii** [comment]
I think this is impossible to fix. Zend_View created properties dynamically. This looks like zend_view is not usable like this in php8.2

**Comment by glensc** [comment]
you can still use the attribute:
- https://php.watch/versions/8.2/readonly-classes#dynamic-properties
- https://php.watch/versions/8.2/AllowDynamicProperties
- https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by Hikariii** [comment]
The `#[AllowDynamicProperties]` attribute would be a nice solution here indeed.

**Comment by Hikariii** [comment]
This would also be a solution for https://github.com/Shardj/zf1-future/blob/release-1.21.4/library/Zend/Form/Element.php#L863-L878

**Comment by glensc** [comment]
The `setAttrib` could be rewritten to store data in `$this->data` container, but it requires the properties are not actually accessed.

**Comment by icyz** [comment]
> you can still use the attribute:
> 
> * https://php.watch/versions/8.2/readonly-classes#dynamic-properties
> * https://php.watch/versions/8.2/AllowDynamicProperties
> * https://php.watch/versions/8.2/dynamic-properties-deprecated

Would this be a temporary solution? or permanent?

**Comment by Hikariii** [comment]
Reading up on https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.dynamic-properties it looks like implementing a __set() and __get() method is more future-proof.

**Comment by Hikariii** [comment]
On the other hand, not using this repository is even way more future-proof

**Comment by icyz** [comment]
> On the other hand, not using this repository is even way more future-proof

but we love this repository, so we have to do the best we can.

**Comment by glensc** [comment]
You can also `extend stdClass` which is written on those links that it already has  `#[AllowDynamicProperties]` set automatically. I don't think either of them is going away. not the attribute nor `stdClass`.  I prefer `#[AllowDynamicProperties]` because it's purpose is distinct, extending `stdCass` may introduce some other unwanted funny bugs.

**Comment by Hikariii** [comment]
I see `#[AllowDynamicProperties]` has already been used. https://github.com/Hikariii/zf1-future/commit/f6f029cf332403536871b997cf59f49820a7e6b0
As I see it this changes the composer requirement to `"php": ">=8.0"` because php7 does not know about attributes. So it looks like an inconsistency has gotten into the codebase, or the composer requirements are not updated.

**Comment by glensc** [comment]
no. `#[AllowDynamicProperties]` doesn't change requirements, because php7 doesn't understand attributes neither does it complain about dynamic properties.

**Comment by Hikariii** [comment]
ok that's good then adding the attribute should be the way to go

**Comment by vijaygarg-ahead** [comment]
Can anyone give a permanent solution to this issue?

**Comment by thijsvdanker** [comment]
The fixes in #261, specifically commit https://github.com/Shardj/zf1-future/pull/261/commits/34331f7faedba5f23521ee50e04bb3ff4cdb6919,  breaks our application.

We have wrapped Laravel around our ZF application and run the Blade compiler after ZF has done it's job.

If `#[AllowDynamicProperties]` keeps the code before https://github.com/Shardj/zf1-future/pull/261/commits/34331f7faedba5f23521ee50e04bb3ff4cdb6919 running that would be great for us 😬

**Comment by glensc** [comment]
@thijsvdanker you need to provide a standalone reproducer for your report to be useful.

**Comment by thijsvdanker** [comment]
@glensc I understand.
I don't really think my usecase is technically sound enough to be part of the discussion. I just wanted to put forward that if all else equal, the "non-breaking" change would have my preference.

**Comment by nunnrlc** [comment]
> The fixes in #261, specifically commit [34331f7](https://github.com/Shardj/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919), breaks our application.
> 
> We have wrapped Laravel around our ZF application and run the Blade compiler after ZF has done it's job.
> 
> If `#[AllowDynamicProperties]` keeps the code before [34331f7](https://github.com/Shardj/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919) running that would be great for us 😬

Same here, broken after putting the `view` dynamic properties into `private $_data = [];` in `library/Zend/View/Abstract.php`
Reason is use of `property_exists()` in our codebase. Luckily only once, and caught in testing, so not a big deal here!

**Actually, I don't mind the zf1-future change, but just to help others I'll explain the fix...**

In our codebase we had `property_exists()` to test for a view variable in a phtml template
```
if (propert_exists($this, 'someViewProperty')) { // $this is the view instance.
  ...
}
```

Well that doesn't work now the dynamic properties are stored in a `__get/__set` array after commit [34331f7](https://github.com/Shardj/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919)

Easily changed our code to fix with `isset()`:
```
if (isset($this->someViewProperty)) { // $this is the view instance.
  ...
}
```

So maybe a mistake to ever use `property_exists` rather than `isset`. The `isset` function plays nicely with `__get/__set`, but `property_exists` is strictly honest about "real" properties. A PHP gotcha I guess.

**Comment by holtkamp** [comment]
When using the ContextSwitch ActionHelper, a 'contextKey' is used which defaults to `contexts`: 

https://github.com/Shardj/zf1-future/blob/7fa9c5f50f0ce8ceecafb13e107eebe4c3d04051/library/Zend/Controller/Action/Helper/ContextSwitch.php#L62

No setters are available to influence the value of the 'contextKey'. 

In various parts of the class it then checks whether this property is set on the Controller and if not, will set it: 

https://github.com/Shardj/zf1-future/blob/7fa9c5f50f0ce8ceecafb13e107eebe4c3d04051/library/Zend/Controller/Action/Helper/ContextSwitch.php#L1145-L1149

I circumvented / resolved this _specific_ deprecation by adding `public array $contexts` property in my own base Controller with a comment about why that property exists. 

But as suggested in https://github.com/Shardj/zf1-future/issues/307#issuecomment-1384350713 `#[AllowDynamicProperties]` could be added to https://github.com/Shardj/zf1-future/blob/7fa9c5f50f0ce8ceecafb13e107eebe4c3d04051/library/Zend/Controller/Action.php

**Comment by hungtrinh** [comment]
This issue resolved here: https://github.com/Shardj/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919 by PR #268
