### ISSUE TITLE
Question: Release strategy

### ISSUE THREAD

**Issue by develart-projects** [Shardj/zf1-future#359]
Hi everyone,

I'm just wondering what is an release strategy for this project? Is there any cycle set, or it's kind of free? :)

Seems like there are some merges to master alraedy, plenty of PRs approved, some even merged.

Thank you.

**Comment by geoalexidis** [comment]
I wonder about that too. Is there a plan for PHP 8.2?

**Comment by develart-projects** [comment]
Seems like maintainers are gone. What about to pick some new ones? Or do we have to create another fork? @Shardj ? 
Too many forks will kill the initiative and seems, that here is plenty of contributors.

**Comment by Shardj** [comment]
@develart-projects sure, I'm happy to give people repo permissions if anyone wants to volunteer as a maintainer. I haven't worked on a project that uses this codebase in almost 2 years now so it fell out of interest for me.

Do tag me in replies, that way I actually get a notification. I don't really look at my GitHub very much currently.

**Comment by develart-projects** [comment]
@Shardj we still have plenty of projects active, so I'm happy to spent some time on this. At least we have already some work done in the PRs waiting just for acceptance and new release, thanks.

**Comment by Shardj** [comment]
@develart-projects alright, added you as a contributor. There are three other contributors as well but it seems they've all stopped looking at this repo too. However I know @kaktusas2598 still works on a project that uses this repo so if you aren't sure on a PR maybe check in with him, or tag me and I'll hopefully see it

To answer the original question, release strat was just whenever. Feel free to make one yourself, [here's](https://github.com/Shardj/zf1-future/commit/5446af3466d1fc3faa32a708af2cdc9baf9fc11a) the most recent release commit if you want to see the files I change. I started the changelog.md because it was requested but it's pretty much just copied and pasted PR titles. After changing the files I just make a new tag for the new versions semvar in the format of "version-#.#.#" and then release on that tag.

**Comment by krzyko** [comment]
Thanks for the continuous support. Releasing new versions please update also \library\Zend\Version.php content.

**Comment by develart-projects** [comment]
@krzyko thanks for the reminder, will try to not forget :)

**Comment by cmelius** [comment]
Good work guys. I am also using this in a big project and I'm happy this is maintained. 
Will try to contribute once we start working to get this running on PHP 8.2
