### ISSUE TITLE
Zend db returning everything as string

### ISSUE THREAD

**Issue by roshanbudhathoki** [Shardj/zf1-future#362]
data fetch from database, every column is returned as string instead of proper data type, even int is returned as string like "1"

**Comment by Jimbolino** [comment]
this is actually recently changed behavior
https://github.com/Shardj/zf1-future/commit/7c3911ca2933c8b57ea0a54d04eca4bfe1d73320

I think its best to revert this commit

**Comment by develart-projects** [comment]
@Jimbolino if I remember correctly, PDO fetch is was always returning strings. Why is this problem anyway? Are we C++ now?

**Comment by develart-projects** [comment]
..or at least was, not sure now. As I'm pretty ignoring types, unless are classes.

**Comment by develart-projects** [comment]
YEp, just checked the docs. Before 8.1 all were strings. So now the question is, if we are going to keep framework consistent or we are going to adjust framework to some enforced typing.

Maybe there is a way in the middle: what about to introduce method to disable stringify? Then we have backwards compatibility and also have possibility to go forward with strict types within framework.

**Comment by Jimbolino** [comment]
afaik since php uses mysqlnd (optional since php 5.3, default in php 5.4) the pdo-mysql driver returns datatypes as they are configured in the database.

I read the migration notes: https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo

- `PDO::ATTR_STRINGIFY_FETCHES now stringifies values of type bool to "0" or "1". Previously bools were not stringified.`
Not sure if mysql has [bool fields](https://dev.mysql.com/doc/refman/8.0/en/data-types.html). I know there are BIT fields. A BIT(1)  can be used as a boolean, but they are a pain to work with because they are returned as binary data. You can however have queries that return "true" or "false", but i'm not sure thats a common use case for most people. 

- `Integers and floats in result sets will now be returned using native PHP types instead of strings when using emulated prepared statements.` 
I'm not sure if zf1 uses "[emulated prepared statements](https://www.php.net/manual/en/pdo.prepare.php#:~:text=escape%20the%20parameters.-,PDO%20will%20emulate%20prepared%20statements,-/bound%20parameters%20for)", afaik [it just concats the strings](https://github.com/Shardj/zf1-future/blob/master/library/Zend/Db/Select.php#L1223) into a query, and executes it as a regular query statement. But im not sure about that.

In general i'm not a big fan of overwriting defaults to stay compatible with older versions. When a developer upgrades their php version, it is their responsibility to check if their code is compatible with the new version (usually by reading a changelog). By putting these defaults in zf1 we become responsible for these backwards incompatible changes. Usually users dont read changelogs when they do a `composer update`, at least i only do it on major releases.
In my case i had to debug code that was written in 2019  and survived upgrades from php 7.0 to php 8.2, but recently broke because of this change :)

@hungtrinh please tell us how you see things :)

**Comment by hungtrinh** [comment]
@Jimbolino I understand your frustration. 

From my point of view, to save time upgrading libraries for many ZF1 based projects, I want to keep everything backward compatible as much as possible

That why I made #324 and #320

### To solve your problem i think you can make an PR: 

1. Replace
   https://github.com/Shardj/zf1-future/blob/7c3911ca2933c8b57ea0a54d04eca4bfe1d73320/library/Zend/Db/Adapter/Pdo/Mysql.php#L113-L119
  By
   ```php
   if (PHP_VERSION_ID >= 80100 && Zend_Db_Adapter_Abstract::$isPdoStringifyFetchesBackwardCompatiblePhp8) { 
       // ensure $config['driver_options'] is an array 
       $this->_config['driver_options'] = $this->_config['driver_options'] ?? []; 
       if (!isset($this->_config['driver_options'][PDO::ATTR_STRINGIFY_FETCHES])) { 
           $this->_config['driver_options'][PDO::ATTR_STRINGIFY_FETCHES] = true; 
       } 
   } 
   ```
2. Add to line 57 public static attribute `public static $isPdoStringifyFetchesBackwardCompatiblePhp8 = true;`
   https://github.com/Shardj/zf1-future/blob/fd9504563846cb081ca9eae98350a0e2ada73feb/library/Zend/Db/Adapter/Pdo/Abstract.php#L45-L57

So in your use case in zf project folder `public/index.php` after line zend autoloading library add this line to solve your problem
That will keep your project in forward compatible with php >= 8
```php
... \\after Zend Framework Autoload library line
Zend_Db_Adapter_Abstract::$isPdoStringifyFetchesBackwardCompatiblePhp8) = false;
``` 

###  Why use static attribute why not use normal property support setting per connection?

Because Project base on ZF1 we have 2 use case only
- Backward Compatible With Php <= 8
- Forward  Compatible With Php >= 8

Use static property flag save time to setting for project in 1 line at 1 startup point.
If we provide normal class attribute flag lead to enable mixed mode: some where in project $isPdoStringifyFetchesBackwardCompatiblePhp8=false other $isPdoStringifyFetchesBackwardCompatiblePhp8=true => it's not safe
