### ISSUE TITLE
Update readme to reflect PHP 8.2 compatibility

### ISSUE THREAD

**Issue by alanseiden** [Shardj/zf1-future#401]
Has anyone here tested with a PHP 8.2 application? Can we say with some certainty that 8.2 or 8.3 will work?  If so, I would like to update the readme. I am being asked if the package can go beyond 8.1.

**Comment by develart-projects** [comment]
As far as I know - partially. Problem with each new PHP (>8) release is, that they are forcing new interface changes for some function groups, enforcing strict types, etc. we already had (and still have) discussion what exactly maintaining of this package really mean, but without any conclusion. And it's getting harder to keep up with newer PHP versions, because are not exactly backwards compatible.

**Comment by alanseiden** [comment]
Thank you... sounds like we have a "best effort" basis and the community needs to contribute as issues are discovered.
@develart-projects In that case, I wonder if we should not specify in the readme that a specific PHP version is supported. e.g. 8.1, which implies that 8.2 is NOT supported. It's more like PHP 8 generally is supported, and fixes are apprecated as issues are discovered. Or we could give a level of confidence. e.g. 8.0: 95% confident. 8.1: 90% confident. 8.2: 80% confident. or a coverage level?

**Comment by develart-projects** [comment]
Actually I'm pretty confident about current 8.1 compatibility, as we are running couple of bigger projects on such servers. Before we ran 7.4. So let's say, that 8.1 is pretty tested.

8.2.. not really. We already have some reports about incompatibile contracts and stuff, quite hard to "fix", because they are clashing with 7.x line. 

Anyway, I agree, that we should include this info into the readme. Actually updating the docs are only thing preventing me to release 1.24.0

**Comment by sreichel** [comment]
> Actually updating the docs are only thing preventing me to release 1.24.0

IMHO, docs should not prevent a new release.

I would keep it as it is for now. PHP8 is pretty tested, but there are still issues (see my latest PR - non-numeric input).

My 2 cents.

**Comment by develart-projects** [comment]
I added the support note.
